/**
 * The one photograph referenced from more than one place.
 *
 * The preloader ends on this frame and the hero opens on it, so they must name the
 * same file — and, because both render it through next/image at the same `sizes`, they
 * resolve to the same optimized URL and the browser downloads it once.
 *
 * The hand-rolled `srcSet` helper that used to live here is gone. It paired every photo
 * with a `-1280` variant generated by `scripts/webp.sh`, which next/image now makes
 * redundant: it derives the whole responsive set from `sizes`. It was also quietly
 * wrong for most of the library — only 34 of the 123 webp files ever had a `-1280`
 * sibling, so the small candidate 404'd for the rest.
 */
export const BOUDHA = "/images/boudha/boudhanath_new.png";

/**
 * Where the cinematic lands: a cracked-plaster wall in the prayer-flag palette
 * (white / gold / terracotta / slate). The film cross-fades from Boudhanath to this,
 * and it is the resting hero's ground.
 */
export const WALL = "/images/preloader/mustang-wall.png";
